development:
  bucket: altbreaks-dev
  access_key_id: AKIAI3ERW53BB44TQDLQ
  secret_access_key: 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
production:
  bucket: altbreaks
  access_key_id: AKIAI3ERW53BB44TQDLQ
  secret_access_key: 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
